import { afterEach, describe, expect, it, vi } from 'vitest';
import { needsTrackingId, signTrackingId } from './donation-tracking';

afterEach(() => {
  vi.unstubAllEnvs();
});

describe('needsTrackingId', () => {
  it('signs an anonymous donation create', () => {
    expect(needsTrackingId('/donations', 'POST', false)).toBe(true);
  });

  it('signs an anonymous donation update', () => {
    expect(needsTrackingId('/donations/don_abc', 'PUT', false)).toBe(true);
  });

  // Authenticated requests are not checked.
  it('leaves an authenticated donation alone', () => {
    expect(needsTrackingId('/donations', 'POST', true)).toBe(false);
  });

  it('leaves reads and other endpoints alone', () => {
    expect(needsTrackingId('/donations/don_abc', 'GET', false)).toBe(false);
    expect(needsTrackingId('/payments', 'POST', false)).toBe(false);
  });

  it('does not match an endpoint that merely starts with the same name', () => {
    expect(needsTrackingId('/donationsummary', 'POST', false)).toBe(false);
  });
});

describe('signTrackingId', () => {
  // Fixed vector generated by the server-side implementation, so the two cannot drift.
  it('matches the server-side digest exactly', async () => {
    vi.stubEnv('NEXT_PUBLIC_TRACKING_KEY', 'test-tracking-key');

    await expect(
      signTrackingId('{"amount":10,"currency":"EUR"}')
    ).resolves.toBe(
      'f53e263397a8f4cc1436dc243f8bfe7bbf6d8d4bb56643e9da4f8a9ad015b388'
    );
  });

  it('returns null with no key, which is the local default', async () => {
    vi.stubEnv('NEXT_PUBLIC_TRACKING_KEY', '');

    await expect(signTrackingId('{}')).resolves.toBeNull();
  });

  it('signs the exact bytes it is given, so whitespace changes the result', async () => {
    vi.stubEnv('NEXT_PUBLIC_TRACKING_KEY', 'test-tracking-key');

    const tight = await signTrackingId('{"a":1}');
    const spaced = await signTrackingId('{"a": 1}');

    expect(tight).not.toBe(spaced);
  });
});
