import type { Theme } from './types';

import { defineBg } from './backgrounds';

export const THEMES: Record<string, Theme> = {
  spring: {
    id: 'spring',
    name: 'Spring Vibes',
    category: 'nature',
    accent: 'emerald',
    mode: 'light',
    bodyFont: 'open-sans',
    titleFont: 'poppins',
    featured: true,
    colorOptions: [
      'emerald',
      'green',
      'teal',
      'cyan',
      'pink',
      'lime',
      'blue',
      'indigo',
    ],
    curatedBgs: ['bg-leaves', 'bg-meadow-loop', 'bg-botanic', 'bg-watercolor'],
    bg: defineBg(
      'bg-gradient-to-br from-emerald-300/25 via-pink-200/20 via-sky-200/15 to-lime-300/20'
    ),
  },
  birthday: {
    id: 'birthday',
    name: 'Birthday Party',
    category: 'celebration',
    accent: 'orange',
    mode: 'light',
    bodyFont: 'open-sans',
    titleFont: 'poppins',
    featured: true,
    colorOptions: [
      'blue',
      'pink',
      'yellow',
      'green',
      'orange',
      'purple',
      'red',
      'indigo',
    ],
    curatedBgs: ['bg-candle', 'bg-balloons', 'bg-cake-loop'],
    bg: defineBg(
      'bg-gradient-to-br from-orange-300/25 via-red-200/20 to-pink-300/20',
      { animation: 'confetti' }
    ),
  },
  wedding: {
    id: 'wedding',
    name: 'Wedding Elegance',
    category: 'celebration',
    accent: 'rose',
    mode: 'light',
    bodyFont: 'open-sans',
    titleFont: 'playfair',
    featured: true,
    colorOptions: [
      'rose',
      'pink',
      'red',
      'purple',
      'indigo',
      'blue',
      'violet',
      'fuchsia',
    ],
    curatedBgs: ['bg-botanic', 'bg-petals', 'bg-paper', 'bg-watercolor'],
    bg: defineBg(
      'bg-gradient-to-br from-rose-300/50 via-pink-200/45 to-purple-100/40',
      {
        decoration: 'pattern',
        pattern_id: 'bg-petals',
        opacity: 0.35,
        animation: 'hearts',
      }
    ),
  },
  stratospheric: {
    id: 'stratospheric',
    name: 'Polar Stratospheric Clouds',
    category: 'atmospheric',
    accent: 'amber',
    mode: 'light',
    bodyFont: 'open-sans',
    titleFont: 'poppins',
    featured: true,
    colorOptions: [
      'yellow',
      'pink',
      'amber',
      'orange',
      'rose',
      'purple',
      'indigo',
      'blue',
    ],
    curatedBgs: ['bg-clouds-loop', 'bg-watercolor', 'bg-paper'],
    bg: defineBg(
      'bg-gradient-to-br from-yellow-100/40 via-pink-100/35 to-purple-100/30'
    ),
  },
  sunset: {
    id: 'sunset',
    name: 'Sunset',
    category: 'nature',
    accent: 'orange',
    mode: 'light',
    bodyFont: 'open-sans',
    titleFont: 'poppins',
    featured: true,
    colorOptions: [
      'orange',
      'amber',
      'pink',
      'purple',
      'blue',
      'rose',
      'red',
      'yellow',
    ],
    curatedBgs: ['bg-clouds-loop', 'bg-watercolor', 'bg-waves'],
    bg: defineBg(
      'bg-gradient-to-br from-amber-200/35 via-orange-200/30 to-blue-300/25'
    ),
  },
  'dark-ocean': {
    id: 'dark-ocean',
    name: 'Dark Ocean',
    category: 'nature',
    accent: 'blue',
    mode: 'dark',
    bodyFont: 'open-sans',
    titleFont: 'poppins',
    featured: true,
    colorOptions: [
      'blue',
      'indigo',
      'slate',
      'cyan',
      'teal',
      'purple',
      'emerald',
      'gray',
    ],
    curatedBgs: ['bg-stars', 'bg-clouds-loop', 'bg-grid', 'bg-waves'],
    bg: defineBg('bg-gradient-to-br from-slate-800 via-blue-900 to-indigo-900'),
  },
  'lush-forest': {
    id: 'lush-forest',
    name: 'Lush Forest',
    category: 'nature',
    accent: 'emerald',
    mode: 'dark',
    bodyFont: 'open-sans',
    titleFont: 'poppins',
    featured: true,
    colorOptions: [
      'emerald',
      'green',
      'teal',
      'cyan',
      'blue',
      'lime',
      'indigo',
      'slate',
    ],
    curatedBgs: ['bg-leaves', 'bg-meadow-loop', 'bg-botanic', 'bg-watercolor'],
    bg: defineBg(
      'bg-gradient-to-br from-green-800 via-emerald-700 to-teal-800',
      { animation: 'snow' }
    ),
  },
  volcanic: {
    id: 'volcanic',
    name: 'Volcanic',
    category: 'nature',
    accent: 'orange',
    mode: 'dark',
    bodyFont: 'open-sans',
    titleFont: 'poppins',
    featured: true,
    colorOptions: [
      'orange',
      'red',
      'yellow',
      'pink',
      'purple',
      'amber',
      'rose',
      'indigo',
    ],
    bg: defineBg('bg-gradient-to-br from-red-900 via-orange-800 to-yellow-700'),
  },
  midnight: {
    id: 'midnight',
    name: 'Midnight',
    category: 'minimal',
    accent: 'slate',
    mode: 'dark',
    bodyFont: 'open-sans',
    titleFont: 'poppins',
    featured: true,
    colorOptions: [
      'slate',
      'gray',
      'zinc',
      'blue',
      'purple',
      'indigo',
      'cyan',
      'teal',
    ],
    bg: defineBg('bg-gradient-to-br from-gray-900 via-slate-800 to-zinc-900'),
  },
  dark: {
    id: 'dark',
    name: 'Professional Dark',
    category: 'business',
    accent: 'blue',
    mode: 'dark',
    bodyFont: 'open-sans',
    titleFont: 'poppins',
    isPlain: true,
    featured: true,
    colorOptions: [
      'blue',
      'slate',
      'gray',
      'zinc',
      'neutral',
      'purple',
      'indigo',
      'cyan',
    ],
    bg: defineBg('bg-gray-900'),
  },
  minimal: {
    id: 'minimal',
    name: 'Minimal',
    category: 'minimal',
    accent: 'gray',
    mode: 'light',
    bodyFont: 'open-sans',
    titleFont: 'poppins',
    isPlain: true,
    featured: true,
    colorOptions: [
      'gray',
      'slate',
      'zinc',
      'neutral',
      'stone',
      'blue',
      'indigo',
      'purple',
    ],
    curatedBgs: ['bg-grid', 'bg-paper', 'bg-waves'],
    bg: defineBg('bg-gray-50'),
  },
};

export const DEFAULT_THEME = THEMES.spring;
