import type { Theme } from './types';

export const THEMES: Record<string, Theme> = {
  spring: {
    id: 'spring',
    name: 'Spring Vibes',
    category: 'nature',
    background:
      'bg-gradient-to-br from-emerald-300/25 via-pink-200/20 via-sky-200/15 to-lime-300/20',
    accent: 'emerald',
    mode: 'light',
    bodyFont: 'open-sans',
    titleFont: 'poppins',
    animation: 'none',
    featured: true,
    colorOptions: [
      'emerald',
      'green',
      'teal',
      'cyan',
      'pink',
      'lime',
      'blue',
      'indigo',
    ],
  },
  clean: {
    id: 'clean',
    name: 'Clean White',
    category: 'minimal',
    background: 'bg-white',
    accent: 'blue',
    mode: 'light',
    bodyFont: 'open-sans',
    titleFont: 'poppins',
    animation: 'none',
    isPlain: true,
    featured: true,
    colorOptions: [
      'blue',
      'emerald',
      'purple',
      'indigo',
      'teal',
      'cyan',
      'slate',
      'gray',
    ],
  },
  dashboard: {
    id: 'dashboard',
    name: 'Dashboard',
    category: 'business',
    background: 'bg-gray-50',
    accent: 'blue',
    mode: 'light',
    bodyFont: 'open-sans',
    titleFont: 'poppins',
    animation: 'none',
    isPlain: true,
    featured: true,
    colorOptions: [
      'blue',
      'indigo',
      'slate',
      'gray',
      'emerald',
      'teal',
      'cyan',
      'purple',
    ],
  },
  birthday: {
    id: 'birthday',
    name: 'Birthday Party',
    category: 'celebration',
    background:
      'bg-gradient-to-br from-orange-300/25 via-red-200/20 to-pink-300/20',
    accent: 'orange',
    mode: 'light',
    bodyFont: 'open-sans',
    titleFont: 'poppins',
    animation: 'confetti',
    colorOptions: [
      'blue',
      'pink',
      'yellow',
      'green',
      'orange',
      'purple',
      'red',
      'indigo',
    ],
  },
  wedding: {
    id: 'wedding',
    name: 'Wedding Elegance',
    category: 'celebration',
    background:
      'bg-gradient-to-br from-rose-300/50 via-pink-200/45 to-purple-100/40',
    accent: 'rose',
    mode: 'light',
    bodyFont: 'open-sans',
    titleFont: 'playfair',
    animation: 'hearts',
    colorOptions: [
      'rose',
      'pink',
      'red',
      'purple',
      'indigo',
      'blue',
      'violet',
      'fuchsia',
    ],
  },
  corporate: {
    id: 'corporate',
    name: 'Corporate',
    category: 'business',
    background:
      'bg-gradient-to-br from-blue-100/30 via-slate-50/20 to-blue-200/25',
    accent: 'blue',
    mode: 'light',
    bodyFont: 'open-sans',
    titleFont: 'poppins',
    animation: 'none',
    colorOptions: [
      'blue',
      'indigo',
      'slate',
      'gray',
      'emerald',
      'teal',
      'cyan',
      'purple',
    ],
  },
  stratospheric: {
    id: 'stratospheric',
    name: 'Polar Stratospheric Clouds',
    category: 'atmospheric',
    background:
      'bg-gradient-to-br from-yellow-100/40 via-pink-100/35 to-purple-100/30',
    accent: 'amber',
    mode: 'light',
    bodyFont: 'open-sans',
    titleFont: 'poppins',
    animation: 'none',
    featured: true,
    colorOptions: [
      'yellow',
      'pink',
      'amber',
      'orange',
      'rose',
      'purple',
      'indigo',
      'blue',
    ],
  },
  sunset: {
    id: 'sunset',
    name: 'Sunset',
    category: 'nature',
    background:
      'bg-gradient-to-br from-amber-200/35 via-orange-200/30 to-blue-300/25',
    accent: 'orange',
    mode: 'light',
    bodyFont: 'open-sans',
    titleFont: 'poppins',
    animation: 'none',
    featured: true,
    colorOptions: [
      'orange',
      'amber',
      'pink',
      'purple',
      'blue',
      'rose',
      'red',
      'yellow',
    ],
  },
  'dark-ocean': {
    id: 'dark-ocean',
    name: 'Dark Ocean',
    category: 'nature',
    background: 'bg-gradient-to-br from-slate-800 via-blue-900 to-indigo-900',
    accent: 'blue',
    mode: 'dark',
    bodyFont: 'open-sans',
    titleFont: 'poppins',
    animation: 'none',
    colorOptions: [
      'blue',
      'indigo',
      'slate',
      'cyan',
      'teal',
      'purple',
      'emerald',
      'gray',
    ],
  },
  'lush-forest': {
    id: 'lush-forest',
    name: 'Lush Forest',
    category: 'nature',
    background: 'bg-gradient-to-br from-green-800 via-emerald-700 to-teal-800',
    accent: 'emerald',
    mode: 'dark',
    bodyFont: 'open-sans',
    titleFont: 'poppins',
    animation: 'snow',
    colorOptions: [
      'emerald',
      'green',
      'teal',
      'cyan',
      'blue',
      'lime',
      'indigo',
      'slate',
    ],
  },
  volcanic: {
    id: 'volcanic',
    name: 'Volcanic',
    category: 'nature',
    background: 'bg-gradient-to-br from-red-900 via-orange-800 to-yellow-700',
    accent: 'orange',
    mode: 'dark',
    bodyFont: 'open-sans',
    titleFont: 'poppins',
    animation: 'none',
    colorOptions: [
      'orange',
      'red',
      'yellow',
      'pink',
      'purple',
      'amber',
      'rose',
      'indigo',
    ],
  },
  midnight: {
    id: 'midnight',
    name: 'Midnight',
    category: 'minimal',
    background: 'bg-gradient-to-br from-gray-900 via-slate-800 to-zinc-900',
    accent: 'slate',
    mode: 'dark',
    bodyFont: 'open-sans',
    titleFont: 'poppins',
    animation: 'none',
    colorOptions: [
      'slate',
      'gray',
      'zinc',
      'blue',
      'purple',
      'indigo',
      'cyan',
      'teal',
    ],
  },
  dark: {
    id: 'dark',
    name: 'Professional Dark',
    category: 'business',
    background: 'bg-gray-900',
    accent: 'blue',
    mode: 'dark',
    bodyFont: 'open-sans',
    titleFont: 'poppins',
    animation: 'none',
    isPlain: true,
    colorOptions: [
      'blue',
      'slate',
      'gray',
      'zinc',
      'neutral',
      'purple',
      'indigo',
      'cyan',
    ],
  },
  minimal: {
    id: 'minimal',
    name: 'Minimal',
    category: 'minimal',
    background: 'bg-gray-50',
    accent: 'gray',
    mode: 'light',
    bodyFont: 'open-sans',
    titleFont: 'poppins',
    animation: 'none',
    isPlain: true,
    colorOptions: [
      'gray',
      'slate',
      'zinc',
      'neutral',
      'stone',
      'blue',
      'indigo',
      'purple',
    ],
  },
};

export const DEFAULT_THEME = THEMES.spring;
