export const DONATION_FORM_ERRORS = {
  'firstName.required': 'firstName.required',
  'firstName.invalid': 'firstName.invalid',
  'lastName.required': 'lastName.required',
  'lastName.invalid': 'lastName.invalid',
  'country.required': 'country.required',
  'country.invalid': 'country.invalid',
  'zipCode.required': 'zipCode.required',
  'zipCode.invalid': 'zipCode.invalid',
  'address.required': 'address.required',
  'address.invalid': 'address.invalid',
  'address2.invalid': 'address2.invalid',
  'city.required': 'city.required',
  'city.invalid': 'city.invalid',
  'state.invalid': 'state.invalid',
  'email.required': 'email.required',
  'email.invalid': 'email.invalid',
  'companyName.required': 'companyName.required',
  'companyName.invalid': 'companyName.invalid',
  'tin.required': 'tin.required',
  'tin.invalid': 'tin.invalid',
  'paymentMethod.required': 'paymentMethod.required',
} as const;

export type DonationFormErrorKey = keyof typeof DONATION_FORM_ERRORS;
